SELECT
    STATE.STATE_ID
  , STATE.STATE_NAME
  , STATE.STATE_KANA
  , REGION.REGION_ID
  , REGION.REGION_NAME
  , REGION.REGION_KANA
FROM
    STATE
  , REGION
WHERE
   REGION.REGION_ID = STATE.REGION_ID
ORDER BY
   REGION.REGION_ID
  ,STATE.STATE_ID;