# デフォルト設定　開発環境(インメモリDBを使用)の設定
spring:
    thymeleaf.cache: false #開発中はキャシュしない
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./data
        username: sa
        password:
    devtools:
      restart:
        enabled: true
doma:
    dialect: H2
    naming: SNAKE_LOWER_CASE
    sql-file-repository: NO_CACHE
#検索条件のプロパティ
search:
    offset: 0
    limit: 500

management.security.enabled: false

---
# 開発環境（ローカルのMySQLを使用）の設定
spring:
    profiles: development_local_mysql
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ADDRESS_SEARCH
        username: pgtop
        password: 12345
        initialize: false #データはDataBaseにあらかじめセットしているためdata.sqlを読み込まない
doma:
    dialect: MYSQL
---
# 本番環境の設定
spring:
    profiles: production
    thymeleaf.cache: true
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://testdb.cxjycaurv1vp.us-west-2.rds.amazonaws.com:3306/ADDRESS_SEARCH
        username: pgtop
        password: 12345
        initialize: false #データはDataBaseにあらかじめセットしているためdata.sqlを読み込まない
doma:
    dialect: MYSQL
    