# デフォルト設定　開発環境(インメモリDBを使用)の設定
spring:
    application:
      name: JapaneseAddressSearcher
    thymeleaf.cache: false #開発中はキャシュしない
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./data
        username: sa
        password:
        sql-script-encoding: UTF-8
    h2:
      console:
        enabled: true
    devtools:
      restart:
        enabled: true
doma:
    dialect: H2
    naming: SNAKE_LOWER_CASE
    sql-file-repository: NO_CACHE
server:
  error:
    include-stacktrace: always
security:
  user:
    name: user
    password: pass
logging:
  file: app.log
management:
  context-path: /actuator
  security:
    enabled: false
#検索条件のプロパティ
search:
    offset: 0
    limit: 500

---
# 開発環境（ローカルのMySQLを使用）の設定
spring:
    profiles: development_local_mysql
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ADDRESS_SEARCH
        username: pgtop
        password: 12345
        initialize: false #データはDataBaseにあらかじめセットしているためdata.sqlを読み込まない
doma:
    dialect: MYSQL
---
# 本番環境の設定
spring:
    profiles: production
    thymeleaf.cache: true
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://testdb.cxjycaurv1vp.us-west-2.rds.amazonaws.com:3306/ADDRESS_SEARCH
        username: pgtop
        password: 12345
        initialize: false #データはDataBaseにあらかじめセットしているためdata.sqlを読み込まない
    devtools:
      restart:
        enabled: true
doma:
    dialect: MYSQL
